### ISSUE TITLE
Convert PersianDate to Calendar format

### ISSUE THREAD

**Issue by ShahabShahab** [Roojin/persian-calendar-view#1]
Hello mr.Mir rajabi

How can I convert a simple persiandate to a calendar type object?
I am trying this code, but this always returns me the current time in millis!
        PersianDate persianDate1 = new PersianDate(1396,3 ,22);
        System.out.println(persianDate1.getTime());
        Date date = DateConverter.persianToCivil(persianDate1);
        Calendar calendar1 = Calendar.getInstance();
        calendar.setTime(date);
        System.out.println(calendar.getTimeInMillis());

**Comment by mirrajabi** [comment]
Hi.
This might be what you're looking for
```java
PersianDate persianDate = new PersianDate(1396,3 ,22);
CivilDate civilDate = DateConverter.persianToCivil(persianDate);
Calendar calendar = (Calendar)Calendar.getInstance().clone();
calendar.set(civilDate.getYear(), civilDate.getMonth()-1, civilDate.getDayOfMonth());
System.out.println(calendar.getTime());
```

**Comment by ShahabShahab** [comment]
Yes exactly!

I got to this solution last day eventually.

Thanks for your time
