### ISSUE TITLE
Xamarin wrapper

### ISSUE THREAD

**Issue by Cloze** [Roojin/persian-calendar-view#11]
Hi,
thank you for this great component.

add xamarin wrapper too, if possible.

**Comment by mirrajabi** [comment]
Hi,
Check if this one helps [https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings](https://marketplace.visualstudio.com/items?itemName=EgorBogatov.XamarinGradleBindings)

**Comment by Cloze** [comment]
oooh dear lord ...
i didn't know about that !!! 
thank you

**Comment by mirrajabi** [comment]
@Cloze close the issue if the problem is solved.
