### ISSUE TITLE
چطوری تاریخ را به میلادی برگردونیم؟

### ISSUE THREAD

**Issue by seyyed-amir** [Roojin/persian-calendar-view#15]
سلام
وقتی رویداد کلیک را فعال میکنم به من یک شیء از  PersianDate میده
چطوری اینو برگردونم به میلادی؟
با کد های خود شما میشه این کار را کرد یا باید از کتابخانه های دیگه ای استفاده کنم؟

**Comment by mirrajabi** [comment]
سلام
DateConverted با استفاده از کلاس 

```java
PersianDate persianDate = new PersianDate(1396,11,7);
CivilDate x = DateConverter.persianToCivil(persianDate);
String civilDate = x.getDayOfMonth() + "-" + x.getMonth() + "-" + x.getYear(); // 27-1-2018
```

**Comment by seyyed-amir** [comment]
من این کد را توی سورس شما پیدا کرده بودم فقط یه سوال برام پیش اومد
چرا وقتی میخواهیم
CivilDate
را به 
Calendar 
تبدیل کنیم باید یک واحد از ماه کم کنیم؟

                Calendar cal = Calendar.getInstance();
                cal.set(Calendar.YEAR, dattt.getYear());
                cal.set(Calendar.MONTH, dattt.getMonth() - 1);
                cal.set(Calendar.DAY_OF_MONTH, dattt.getDayOfMonth());

موقع تبدیل متوجه شدم که بعد از تبدیل یک ماه جلوتر نشون داده میشه
فکر کنم خود شما هم ماه را یک واحد کم میکردید
نفهمیدم چرا باید یک واحد کسر بشه!؟؟

**Comment by mirrajabi** [comment]
اون دسته کلاس های مربوط به تاریخ رو من ننوشتم و نمیدونم دلیلش چی بوده.
