### ISSUE TITLE
توابع ماه بعد و قبل برعکس عمل میکنند

### ISSUE THREAD

**Issue by seyyed-amir** [Roojin/persian-calendar-view#16]
سلام دوست من
ضمن تشکر از شما بابت کتابخانه مفیدی که نوشتید

توابع ماه بعدی و ماه قبلی برعکس عمل میکنند

@Override
        public void onClick(View view) {
            int i = view.getId();
            if(i == R.id.nextMonth)
            {
                persianCalendarView.goToPreviousMonth();
            }
            else if(i == R.id.prevMonth)
            {
                persianCalendarView.goToNextMonth();
            }
        }

**Comment by mirrajabi** [comment]
سلام
این تیکه کد توی پروژه نیست. و چک کردم پروژه رو و داره درست کار میکنه. اگه مطمئنی که جایی میلنگه توضیح دقیق تر بده که متوجه شم مشکل دقیقا چیه

**Comment by seyyed-amir** [comment]
کدی که من قرار دادم از پروژه خودم هست
اگر دقت کنید در زمان کلیک شدن
nextMonth
در پروژه خودم متد
persianCalendarView.goToPreviousMonth();
را فراخوانی کردم برای رفتن به ماه بعد
و برعکس...
و واقعا هم اینطوری پاسخ صحیح داد
نفهمیدم چرا این اتفاق می افته..

**Comment by mirrajabi** [comment]
آیدی دکمه ها رو چک کردی ببینی درسته جاهاشون؟
ینی مطمئنی که اون دکمه داره درست کار میکنه؟

**Comment by seyyed-amir** [comment]
بله دقیقا

<com.view.MTextView
                android:id="@+id/prevMonth"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="ماه قبل"
                android:layout_weight="1"
                android:gravity="center"
                android:padding="10dp"
                android:textColor="@color/appThemeColor_hover_2"
                />

            <com.view.MTextView
                android:id="@+id/nextMonth"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="ماه بعد"
                android:layout_weight="1"
                android:gravity="center"
                android:padding="10dp"
                android:textColor="@color/appThemeColor_hover_2"
                />

**Comment by mirrajabi** [comment]
درسته.
چند دقیقه دیگه میتونی از نسخه جدید استفاده کنی

**Comment by me1246** [comment]
با درود ، ممنون از آقای میررجبی به خاطر زحماتتون،، از آقای سید امیر خواستم بپرسم چطور میتونم ازnextmonth استفاده کنم؟ من یک اکتیویتی ساختم به این صورت  
 <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/next_month"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:baselineAligned="false"
            android:src="@drawable/ic_launcher_left_gray" />
        <com.msam.mypersiancalendar.CustomCalendarActivity
            android:id="@+id/custom_calendar"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
        </com.msam.mypersiancalendar.CustomCalendarActivity>
        <View
            android:id="@+id/previous_month"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:baselineAligned="false"
            android:contentDescription="@string/todo"
            android:src="@drawable/ic_launcher_right_gray" />
    </LinearLayout>  
کجا اشتباه کردم که ماه قبلی و بعدی خالی میاره ودرست کار نمیکنه

**Comment by seyyed-amir** [comment]
منظورتون از خالی میاره چی هست؟
توی ui نشون نمیده؟

**Comment by me1246** [comment]
یعنی اطلاعات تقویم رو دیگه نشون نمیده و یک  لیوت خالی میاره،و بعد دیگه همش خالی میاره ، چه دکمه ماه بعد و بزنم چه قبل ؛

**Comment by me1246** [comment]
میشه لطفن فقط بگید دکمه های قبل و بعد رو کجای برنامه تقویم گذاشتید ممنون میشم

**Comment by me1246** [comment]
@seyyed-amir
