### ISSUE TITLE
مشکل کامل کردن تقویم 

### ISSUE THREAD

**Issue by me1246** [Roojin/persian-calendar-view#17]
با درود ، ممنون از آقای میررجبی به خاطر زحماتتون،خواستم بپرسم چطور میتونم ازnextmonth استفاده کنم؟ من یک اکتیویتی ساختم به این صورت  
 <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/next_month"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:baselineAligned="false"
            android:src="@drawable/ic_launcher_left_gray" />
        <com.msam.mypersiancalendar.CustomCalendarActivity
            android:id="@+id/custom_calendar"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
        </com.msam.mypersiancalendar.CustomCalendarActivity>
        <View
            android:id="@+id/previous_month"
            android:layout_width="20dp"
            android:layout_height="20dp"
            android:baselineAligned="false"
            android:contentDescription="@string/todo"
            android:src="@drawable/ic_launcher_right_gray" />
    </LinearLayout>  
کجا اشتباه کردم که ماه قبلی و بعدی خالی میاره ودرست کار نمیکنه؟ یا کجا باید بذارم که درست کار کنه؟ ممنوم میشم

**Comment by mirrajabi** [comment]
سلام
```xml
<com.msam.mypersiancalendar.CustomCalendarActivity
        android:id="@+id/custom_calendar"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
</com.msam.mypersiancalendar.CustomCalendarActivity>
```
این ویو که اصلا  مال کتابخونه ی من نیست. از کجا اومده این؟
```

**Comment by me1246** [comment]
اینو  از کتابخونه شما استفاده کردم، چون دارم تستی کار میکنم برای آموزش کدهاشو سعی کردم بیشتر بنویسم تو برنامه خودم، به جای ایمپورت  ،

**Comment by mirrajabi** [comment]
خب در اینصورت که سمت خودت داری بازنویسی یا کپی پیست میکنی من کاری از دستم بر نمیاد.
سوال بی ربط به کتابخونه محسوب میشه.
