### ISSUE TITLE
اوقات شرعی

### ISSUE THREAD

**Issue by Hitexroid** [Roojin/persian-calendar-view#19]
اوقات شرعی نسبت منطقه رو چطور میشه گرفت

**Comment by mirrajabi** [comment]
اوقات شرعیِ چی؟

**Comment by Hitexroid** [comment]
مثلا تاریخ 1396/12/16 برای شهر بجنورد اذان صبح ساعت 4:49

با این کتابخونه
https://github.com/SaeedMasoumi/Oghat
میشه

اما نزدیک به 500 کیلوبایت میشه حجم فایل جار

**Comment by mirrajabi** [comment]
سوال بی ربطه.

**Comment by Hitexroid** [comment]
چرا بی ربط باشه اینجام هست :/
https://github.com/ebraminio/DroidPersianCalendar

اوکی مرسی
