### ISSUE TITLE
تغییرات ظاهری اعمال نمیشود

### ISSUE THREAD

**Issue by teymoori** [Roojin/persian-calendar-view#2]
سلام. متشکر از لایببری خوبتون
من وقتی داخل جاوا میخوام تغییرات ظاهری عمال کنم تغییرات اعمال نمیشه
 

>         calendarHandler.setTodayBackground(R.color.red_bg);
        calendarHandler.setColorBackground(R.color.green_bg);
        calendarHandler.setColorNormalDay(R.color.gold_base);

        calendarView.update();

**Comment by teymoori** [comment]
و اینکه چطوری میتونم تمام رخدادهای دیفالت رو حذف کنم و فقط رخدادهای خودم رو داشته باشم. یعنی از لحاظ ظاهری فقط رخدادهایی که خودم ادد کردم رو تغییر شکل بدم برای روزها.

**Comment by mirrajabi** [comment]
@teymoori 
سلام و ممنون از فیدبکتون
علت این هست که شما پارامتری که بعنوان رنگ معرفی میکنید در حقیقت آیدی اون ریسورس هست.
لازمه که کدتون رو به یه چیزی مثل این تغییر بدید.
```java
calendarHandler.setColorBackground(getResources().getColor(R.color.green_bg));
calendarHandler.setColorNormalDay(getResources().getColor(R.color.gold_base));
calendarView.update();
```

البته بنده مشکلی رو مشاهده کردم الان که در حال حل اون هستم و اون این هست که رنگ پس زمینه بلافاصله تغییر نمیکنه.

برای سوال دوم هم شما میتونین برای اینکه فقط رویداد هایی که خودتون اضافه کردید رو دریافت کنین و نشون بدین از این تابع استفاده کنید `getLocalEvents`

گرچه حس میکنم منظور زیر خط دار نشدن رویداد های اصلی هست که در این صورت بنده سعی میکنم یه آپشن برای تغییر این حالت هم همراه با فیکس مشکل قبلی به ورژن بعدی اضافه کنم.

**Comment by teymoori** [comment]
متشکرم. من بجای گریدل از خود لایبرری استفاده کردم و تغییرات رو در آداپترتون اعمال کردم.
فعلا کارم راه افتاده. 
اگر  پروژه کامیت شد از سمت شما، برمیگردم رو هموی آدرس گریدلتون.

متشکرم.
عالی هستید.
👍

**Comment by mirrajabi** [comment]
تغییرات اعمال شد و میتونین از نسخه `1.2` استفاده کنید.
از توابع زیر برای نشان دادن یا پنهان کردن خط زیر رویداد های رسمی و شخصی(محلی) روی هَندلر استفاده کنید.

`setHighlightLocalEvents(boolean highlightLocalEvents)` برای رویداد های رسمی
`setHighlightOfficialEvents(boolean highlightOfficialEvents)` برای رویداد های محلی

**Comment by teymoori** [comment]
متشکر
مشکل بعدی استفاده از تابع update  هستش
بعد از اینه رخداد اضافه میکنم و آپدیت زو صدا میکنم تغییری انجام نمیشه
باید دو تا صفحه swipe  کنم
تا فرگمنت اینولیدیت بشه

**Comment by mirrajabi** [comment]
این مشکل اگر مربوط به تغییر رنگ پس زمینه هست تو همین نسخه رفع شده.

**Comment by mirrajabi** [comment]
ظاهرا مشکل این نیست.
در اسرع وقت بررسی میکنم اون حالت رو

**Comment by mirrajabi** [comment]
از نسخه `1.2.1` استفاده کنید. در این نسخه مشکل اعمال نشدن تغییرات بر روی رویداد ها رفع شده است. البته تقویم مجددا رسم میشود و کاملا بهینه نیست.
