### ISSUE TITLE
کار با تقویم

### ISSUE THREAD

**Issue by mitraa1** [Roojin/persian-calendar-view#20]
با سلام ، ممنون به خاطر زحمااتتون  ، یکم پیچیده است،میشه کمی توضیج بدید چطوری کار میکنه؟

**Comment by mirrajabi** [comment]
سلام. تا جایی که میتونستم توضیح دادم. بیشتر از این امکانش نیست.

**Comment by mitraa1** [comment]
وتو فرگونت ازش برای فراخوانی  ,  fragment_month روگذاشتم توی  next , previos ممتونم  از شما،من دکمه
goToPreviousMonth وgoToNextMonth 
استفاده کردم ولی کار نمیکنه،
