### ISSUE TITLE
چند خط در داکیومنت ایراد داد

### ISSUE THREAD

**Issue by muhammadali-karami** [Roojin/persian-calendar-view#21]
سلام ممنون از لطفتون بابت این کتابخانه. لطفا چند خط کد زیر را در داکیومنت درست بفرمایید. بنده موقع استفاده از لایبرری بهش برخوردم. ممنون

  PersianCalendarView calendarView  = (PersianCalendarView) findViewById(R.id.persian_calendar);
  PersianCalendarHandler calendarHandler = persianCalendarView.getCalendar();
                PersianDate today = calendar.getToday();

با این عوض شود:
   PersianCalendarView persianCalendarView  = (PersianCalendarView) findViewById(R.id.persianCalendarView);
        PersianCalendarHandler calendarHandler = persianCalendarView.getCalendar();
        PersianDate today = calendarHandler.getToday();

**Comment by mirrajabi** [comment]
سلام. مشکل اینی که هست الان چیه؟
الان اینه:
```java
PersianCalendarView persianCalendarView  = (PersianCalendarView)findViewById(R.id.persian_calendar);
PersianCalendarHandler calendar = persianCalendarView.getCalendar();
PersianDate today = calendar.getToday();
```

**Comment by muhammadali-karami** [comment]
مشکل تو نام متغیراست وقتی میاری تو محیط کد متوجه میشید. ممنون

**Comment by mirrajabi** [comment]
متوجه نمیشم.
