### ISSUE TITLE
pcv_HeadersFontSize not found.

### ISSUE THREAD

**Issue by mehdir32** [Roojin/persian-calendar-view#24]
سلام
   رو مقدار میدم ارور میده : app:pcv_HeadersFontSize="25dp"وقتی اتریبیوت 
Error:attribute 'ir.korandco.mehdi.pregnancy:pcv_HeadersFontSize' not found.
لطفا راهنمایی کنید

**Comment by mirrajabi** [comment]
سلام
 attr.xml  از ظاهر ارور مشخصه که فایل
 رو به پروژت اضافه نکردی. در همین حین جا داره اشاره کنم که اگه از پروژه مستقیما(با دیپندنسی جیت پک) 
 استفاده نمیکنی و خودت کلون میکنی و تغییر میدی توضیح دادنش با من نیست و از حوضه مشکلات من خارجه.

**Comment by mirrajabi** [comment]
pcv_headersFontSize
حرف اول حروف کوچیک headers

**Comment by mehdir32** [comment]
اره با حروف کوچک میاس باشه البته توی توضیحات با حروف بزرگ نوشته بودید
با تشکر از کتابخونه خوبت

**Comment by mirrajabi** [comment]
Updated readme.
