### ISSUE TITLE
تغییر دایره دور روزهای هفته

### ISSUE THREAD

**Issue by mehdir32** [Roojin/persian-calendar-view#25]
سلام 
میخواستم به جای دایره دور روزهای هفته مربع باشه چطور میشه این کار رو کرد؟

**Comment by mirrajabi** [comment]
سلام.
https://github.com/Roojin/persian-calendar-view#attributes: رجوع شود به

**Comment by mirrajabi** [comment]
pcv_todayBackground
pcv_selectedDayBackground
