### ISSUE TITLE
بدست آوردن سال

### ISSUE THREAD

**Issue by soniya94** [Roojin/persian-calendar-view#29]
سلام. چطوری میتونیم سال رو از روی این کتابخونه بدست بیاریم؟ تابعی برای بدست اوردن سال در این کتابخونه نوشته شده یا خودمون باید یه تابع براش بنویسیم؟

**Comment by mirrajabi** [comment]
See Sample app's [MainActivity](https://github.com/Roojin/persian-calendar-view/blob/master/app/src/main/java/ir/mirrajabi/pc/sample/MainActivity.java)

```java
        final PersianCalendarView persianCalendarView  = (PersianCalendarView)findViewById(R.id.persian_calendar);
        final PersianCalendarHandler calendar = persianCalendarView.getCalendar();
        final PersianDate today = calendar.getToday();
```

 میتونی سال رو بدست بیاری.`today.getYear()` با
