### ISSUE TITLE
تبدیل یونیکس تایم استمپ به تاریخ شمسی

### ISSUE THREAD

**Issue by mehdir32** [Roojin/persian-calendar-view#30]
سلام
ایا تابعی وجود داره که بتونم  تایم استمپ رو به  تاریخ شمسی با فرمت کامل نمایش بدم؟

**Comment by mirrajabi** [comment]
سلام
مستقیما نه. و هدف این کتابخونه ام این نیست که همه جور تبدیلات رو در اختیار دولوپر قرار بده.

ولی میتونی این کارو کنی:

```java
Calendar calendar = Calendar.getInstance();
calendar.setTimeInMillis(timestamp);
CivilDate civilDate = new CivilDate(calendar);
PersianDate persianDate = DateConverter.civilToPersian(civilDate);
```
