### ISSUE TITLE
مشکل هنگام نشان دادن view

### ISSUE THREAD

**Issue by ehsanTC** [Roojin/persian-calendar-view#4]
سلام
برای شروع استفاده از این کتابخانه، آن را در یک اکتیویتی قرار دادم. مثل زیر:

**Test.xml**

```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent"
              xmlns:app="http://schemas.android.com/tools"
              android:orientation="vertical">

    <ir.mirrajabi.persiancalendar.PersianCalendarView
        android:id="@+id/persian_calendar"
        android:layout_width="match_parent"
        android:layout_height="290sp"
        app:pcv_colorBackground="#292929"
        app:pcv_colorDayName="#bab6b6"
        app:pcv_colorHoliday="#ffd506"
        app:pcv_colorHolidaySelected="#f1f2f3"
        app:pcv_colorNormalDaySelected="#d9d9d9"
        app:pcv_colorNormalDay="#f3f4f5"
        app:pcv_eventUnderlineColor="#02f0f0"
        app:pcv_fontSize="20sp"
        app:pcv_headersFontSize="14sp"/>
</LinearLayout>
```

**Test.java**

```java
public class Test extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.test);

    }
}
```

هنگام نمایش اکتیویتی، خطای زیر را نشان می دهد:
```
android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class ImageView
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                at ir.mirrajabi.persiancalendar.core.fragments.MonthFragment.onCreateView(MonthFragment.java:39)
```
مشکل را چطور میشه حل کرد؟

**Comment by mirrajabi** [comment]
`#15: Error inflating class ImageView` این
کنه Inflate رو ImageView نمیتونه  xml میگه تو خط 15 یه
ای وجود نداره رابطه ی منطقی ای بینشون نیست.ImageView با توجه به اینکه توی این کتابخونه هیچ 

 تمام سورسش همینه؟ `test.xml` آیا
لطفا توضیحات بیشتری ارایه شود.

**Comment by ehsanTC** [comment]
بله. برای منم عجیبه. چون تمام کدی که برای اکتیویتی تست استفاده کردم همینه. البته پروژه خیلی بزرگه
سعی می کنم پروژه 
sample 
خودتون را اجرا بگیرم، تا ببینم مشکل پیش میاد یا نه

**Comment by mirrajabi** [comment]
نتیجه رو هم اگه امکانش هست اعلام کن که دستمون بیاد مشکل از چی بوده.

**Comment by ehsanTC** [comment]
من این کارها رو انجام دادم:

1. تبدیلش به یک لایبراری مجزا
2. گرفتن خروجی به صورت Jar

ولی مشکل فوق حل نشد. دلیلش را خودم نفهمیدم ولی حدس میزنم چون پروژه م خیلی بزرگه و کلاس های همنام داشته باشم گریدل یه جایی به مشکل می خوره
نهایتا من تمام کدهای را وارد پروژه م کردم. ولی بصورت یک ماژول جداگانه نشد

**Comment by ehsanTC** [comment]
یه سوال دیگه:
در صورتیکه بخوام در کلاس 
MonthAdapter
شماره ماه فعلی را بفمم، چطور می تونم؟
ممنون

**Comment by mirrajabi** [comment]
کاش اینو تو یه ایشوی جدید مطرح میکردی.
هنوز پیاده سازی نشده OnDemand در حال حاضر یه چنین حالتی وجود داره ولی حالت  
```java
persianCalendarView.getCalendar()
    .setOnMonthChangedListener(new OnMonthChangedListener() {
        @Override
        public void onChanged(PersianDate date) {
            Toast.makeText(MainActivity.this, calendar.getMonthName(date),Toast.LENGTH_SHORT).show();
        }
    });
```

**Comment by ehsanTC** [comment]
من دارم لایبراری شما را یکم دستکاری می کنم تا بتونم روزهای انتخابیم را به جای یه روز چند روز باشه.
برای هر 
MonthAdapter
باید روزهای انتخابی را جدا کنم.

اگه موفق شدم کدش را براتون می فرستم.
در کل پیشنهاد می کنم در آینده این ویژگی ها را اضافه کنید:

1- استفاده از کلاس
PersianCalendarHandler
بصورت خصوصی و اضافه کردن تمام ویژگی های آن به کلاس اصلی
PErsianCalendarView

2- مجزا کردن کارکردهای اصلی
PersianCalendarHandler
به یو آی و حذف برخی متدهایی که برای تغییر زمان استفاده می کنید

3- اضافه کردن متدهای زیر (البته ممکنه فقط مشتریش من باشم)
PersianCalendarView.setMultiSelection(boolean multiSelect)
PersianCalendarView.getSelectedDays(int month)

4- تمام کلاس هایی که برای نشان دادن تاریخ استفاده شدن میشد با کتابخانه زیر جایگزین شوند. من ازش خیلی استفاده کردم و راضیم
https://github.com/mortezaadi/persian-calendar

در کل اگه یه 
Refinement
انجام بدین خیلی عالیه

ممنون

**Comment by mirrajabi** [comment]
ممنون بابت توضیح کامل. حتما تو ذهنم هست این تغییرات ولی متاسفانه وقتم اصلا آزاد نیست.
مثلا اینکه هندلر یه اینستنسه استاتیکه مشکله عظیمیه که اجازه ی داشتن چند تقویم همزمان رو نمیده.
 مطرح کنید که بچسبونم PR  خیلی اتفاقا مشتاق مشارکت سایر دولوپر ها هستم و اگه تغییراتی دارین حتما در قالب.

**Comment by ehsanTC** [comment]
مشکل کدی که من داشتم این بود، که دقیقا فایلی همنام
month_fragment 
در یکی از پروژه هایی که اد کرده بودم وجود داشت. اون فایل را که تغییر نام دادم مشکل حل شد

**Comment by tayebehhosseini** [comment]
سلام. روز بخیر. بابت کتابخانه خیلی ممنون. واقعا عالیه. فقط یه مشکل بوجود آمده. چیزی که از تابع getDayOfWeek متوجه شدم روز در هفته رو به شکل عدد نشون میده. مثلا برای تاریخ 1 خرداد 97 که روز سه شنبه هست عدد 5 رو برمیگردونه. و برای بقیه روزها هم به همین ترتیب مثلا اگر روز مورد نظر جمعه باشه این تابع عدد 1 رو برمیگردونه. من با همین روال جلو می رفتم اما متوجه شدم از 1 مرداد 97 به بعد یکی عقب میفته و کل برنامه هام به هم میریزه. 1 مرداد دوشنبه است و باید عدد 4 بده اما عدد 3 رو برمیگردونه. مشکل از کجاست؟

**Comment by tayebehhosseini** [comment]
سلام. با calendar.getWeekDayName حل شد.
