### ISSUE TITLE
اضافه کردن تقویم درون یک فرگمنت

### ISSUE THREAD

**Issue by hrsalehi** [Roojin/persian-calendar-view#6]
تقویم داخل فرگمنت ها اضافه نمیشود. با افزودن تقویم درون یک فرگمنت ظاهرا کد تولید ظاهر در حلقه بینها گیر میکند.
احتمالا ایراد در عدم تشخیص نیاز به استفاده از fragmentManager() در مقابل childFragmentManager() باشد

**Comment by mirrajabi** [comment]
سوالت اصلا واضح نیست.
 توضیح بیشتر یا نمونه کد یا لاگ ارور میتونه کمک کنه متوجه شم داستان چیه

**Comment by hrsalehi** [comment]
ارور خاصی نمیده
مثالش اینه یه فرگمنت بزارید داخل مثال خودتون و تقویم رو داخل اون لود کنید.
اپلیکیشن فریز خواهد شد.

**Comment by hrsalehi** [comment]
بررسی میکنم اگر مشکل رو متوجه شدم بهتون اطلاع میدم احساس میکنم مشکل از سمت من ناشی میشه

**Comment by hrsalehi** [comment]
با عرض معذرت مشکل از جانب خودم بود و رفع شد
