### ISSUE TITLE
تغییر فونت تقویم

### ISSUE THREAD

**Issue by MansoorJafari** [Roojin/persian-calendar-view#8]
سلام وقتتون بخیر
ببخشید میشه فونت تقویم رو عوض کرد؟؟؟

**Comment by mirrajabi** [comment]
سلام
: بذار و بعدش assets بله. فونت رو توی پوشه ی 
`app:pcv_typefacePath` از این استفاده کن 

```xml
<ir.mirrajabi.persiancalendar.PersianCalendarView
   ...
   app:pcv_typefacePath
   .../>
```

یا توی کدت، روی هندلرِ تقویم، از این تابع استفاده کن:

```java
PersianCalendarHandler#setTypeface(Typeface typeface)
```

**Comment by MansoorJafari** [comment]
تشکر
